version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=true" # False desativa o assistente de configuração inicial
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
